### PR TITLE
Add marked settings to options

### PR DESCRIPTION
**Pull request by DanielLarsenNZ**
This allows marked options to be set from Gruntfile options. See also https://github.com/brainshave/zetzer/pull/2

### CODE REVIEW

**Comment by DanielLarsenNZ** [comment]
@brainshave - not sure what would be useful to test here but open to suggestions.

**Comment by brainshave** [comment]
I think it'd be useful to write an integration test in a form of a fixture and then test it with zetzer `npm link`-ed.

"How to" about fixtures:

https://github.com/brainshave/grunt-zetzer#contributing

If any of it is ambiguous/confusing, plz let me know. Fixtures are picked up automatically by test, make sure it fails first ofc :-) (before `npm link` step)

**Comment by DanielLarsenNZ** [comment]
Nice - thanks, will do.

**Comment by DanielLarsenNZ** [comment]
Marked has GFM and Tables on by default so this PR is not required.

**Pull request closed without merging**
